# Generated by Django 3.1.7 on 2021-04-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
    ]
